server:
  port: 5678

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springBoot?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
      allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册


# 打印SQL
logging:
  level:
    com.example.demo.dao: debug

mybatis:
  # XML扫描路径
  mapper-locations: classpath:mapper/**/*.xml
  # 通用Mapper的方法会自动转换驼峰，但手写的SQL需要开启才能转换
  configuration:
    map-underscore-to-camel-case: on
