server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/p_platform?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456

mqtt:
  host: tcp://broker.emqx.io:1883
  username: admin
  password: public

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-prefix: repository.
    # 在控制台中打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
